services:
  my-backend-car-project:
    build: .
    image: 'my-car-project-image-iso'
    container_name: 'my-car-project-container'
    ports:
      - "3698:8080"
    environment:
      - TZ=Asia/Almaty
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5436/carProjectDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  db:
    image: postgres:latest
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=carProjectDB
    ports:
      - "5436:5432"

  db-test:
    image: postgres:latest
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testCarProjectDB
    ports:
      - "5437:5432"
